/// <reference path="./scratch-vm.d.ts" />
/// <reference path="./scratch-render.d.ts" />
/// <reference path="./scratch-blocks.d.ts" />

/**
 * Only exists in files generated by the packager.
 *
 * The intended way to use this is:
 * if (typeof scaffolding !== 'undefined') {
 *   // in packager
 * }
 *
 * Outside of the packager, trying to access scaffolding any other way will throw a
 * reference error, not return undefined (TypeScript does not let us type that unfortunately)
 */
declare const scaffolding: unknown | undefined;

/**
 * In desktop app, prompt() returns a Promise. Thus you should always do `await prompt(...)` which
 * will work in all environments.
 */
declare function prompt(
  message?: string,
  _default?: string,
): string | null | Promise<string | null>;

/**
 * The global Scratch namespace.
 */
declare namespace Scratch {
  /**
   * The Scratch VM.
   */
  const vm: VM;
  /**
   * The Scratch Renderer.
   */
  const renderer: RenderWebGL;

  // Permission requests here always return a promise, but the security manager methods themselves
  // can return either a boolean or promise.
  function fetch(url: string, options?: RequestInit): Promise<Response>;
  function canFetch(url: string): Promise<boolean>;
  function openWindow(url: string, features?: string): Promise<Window | null>;
  function canOpenWindow(url: string): Promise<boolean>;
  function redirect(url: string): Promise<void>;
  function canRedirect(url: string): Promise<boolean>;
  function canRecordAudio(): Promise<boolean>;
  function canRecordVideo(): Promise<boolean>;
  function canReadClipboard(): Promise<boolean>;
  function canNotify(): Promise<boolean>;
  function canGeolocate(): Promise<boolean>;
  function canEmbed(): Promise<boolean>;
  function canUnsandbox(): Promise<boolean>;
  function canScreenshotCamera(): Promise<boolean>;
  function canDownload(url: string, name: string): Promise<boolean>;
  function download(url: string, name: string): Promise<void>;

  /**
   * Methods for working with colors.
   */
  namespace Color {
    /**
     * An object representing a color in RGB format.
     */
    interface RGBObject {
      /**
       * the red component, in the range [0, 255].
       */
      r: number;

      /**
       * the green component, in the range [0, 255].
       */
      g: number;

      /**
       * the blue component, in the range [0, 255].
       */
      b: number;
    }

    /**
     * An object representing a color in HSV format.
     */
    interface HSVObject {
      /**
       * hue, in the range [0-359).
       */
      h: number;

      /**
       * saturation, in the range [0,1].
       */
      s: number;

      /**
       * value, in the range [0,1].
       */
      v: number;
    }

    /**
     * The color black. [0,0,0]
     */
    const RGB_BLACK: RGBObject;

    /**
     * The color white. [255,255,255]
     */
    const RGB_WHITE: RGBObject;

    /**
     * Convert a Scratch decimal color to a hex string, #RRGGBB.
     * @param {number} decimal RGB color as a decimal.
     * @return {string} RGB color as #RRGGBB hex string.
     */
    function decimalToHex(decimal: number): string;

    /**
     * Convert a Scratch decimal color to an RGB color object.
     * @param {number} decimal RGB color as decimal.
     * @return {RGBObject} rgb - {r: red [0,255], g: green [0,255], b: blue [0,255]}.
     */
    function decimalToRgb(decimal: number): RGBObject;

    /**
     * Convert a hex color (e.g., F00, #03F, #0033FF) to an RGB color object.
     * @param {string} hex Hex representation of the color.
     * @return {RGBObject} null on failure, or rgb: {r: red [0,255], g: green [0,255], b: blue [0,255]}.
     */
    function hexToRgb(hex: string): RGBObject;

    /**
     * Convert an RGB color object to a hex color.
     * @param {RGBObject} rgb - {r: red [0,255], g: green [0,255], b: blue [0,255]}.
     * @return {string} Hex representation of the color.
     */
    function rgbToHex(rgb: RGBObject): string;

    /**
     * Convert an RGB color object to a Scratch decimal color.
     * @param {RGBObject} rgb - {r: red [0,255], g: green [0,255], b: blue [0,255]}.
     * @return {number} Number representing the color.
     */
    function rgbToDecimal(rgb: RGBObject): number;

    /**
     * Convert a hex color (e.g., F00, #03F, #0033FF) to a decimal color number.
     * @param {string} hex Hex representation of the color.
     * @return {number} Number representing the color.
     */
    function hexToDecimal(hex: string): number;

    /**
     * Convert an HSV color to RGB format.
     * @param {HSVObject} hsv - {h: hue [0,360), s: saturation [0,1], v: value [0,1]}
     * @return {RGBObject} rgb - {r: red [0,255], g: green [0,255], b: blue [0,255]}.
     */
    function hsvToRgb(hsv: HSVObject): RGBObject;

    /**
     * Convert an RGB color to HSV format.
     * @param {RGBObject} rgb - {r: red [0,255], g: green [0,255], b: blue [0,255]}.
     * @return {HSVObject} hsv - {h: hue [0,360), s: saturation [0,1], v: value [0,1]}
     */
    function rgbToHsv(rgb: RGBObject): HSVObject;

    /**
     * Linear interpolation between rgb0 and rgb1.
     * @param {RGBObject} rgb0 - the color corresponding to fraction1 <= 0.
     * @param {RGBObject} rgb1 - the color corresponding to fraction1 >= 1.
     * @param {number} fraction - the interpolation parameter. If this is 0.5, for example, mix the two colors equally.
     * @return {RGBObject} the interpolated color.
     */
    function mixRgb(
      rgb0: RGBObject,
      rgb1: RGBObject,
      fraction: number,
    ): RGBObject;
  }

  /**
   * Methods for casting types.
   */
  namespace Cast {
    /**
     * Scratch cast to number.
     * Treats NaN as 0.
     * In Scratch 2.0, this is captured by `interp.numArg.`
     * @param {*} value Value to cast to number.
     * @return {number} The Scratch-casted number value.
     */
    function toNumber(value: unknown): number;

    /**
     * Scratch cast to string.
     * @param {*} value Value to cast to string.
     * @return {string} The Scratch-casted string value.
     */
    function toString(value: unknown): string;

    /**
     * Scratch cast to boolean.
     * In Scratch 2.0, this is captured by `interp.boolArg.`
     * Treats some string values differently from JavaScript.
     * @param {*} value Value to cast to boolean.
     * @return {boolean} The Scratch-casted boolean value.
     */
    function toBoolean(value: unknown): boolean;

    /**
     * Compare two values, using Scratch cast, case-insensitive string compare, etc.
     * In Scratch 2.0, this is captured by `interp.compare.`
     * @param {*} v1 First value to compare.
     * @param {*} v2 Second value to compare.
     * @returns {number} Negative number if v1 < v2; 0 if equal; positive otherwise.
     */
    function compare(v1: unknown, v2: unknown): number;

    /**
     * Cast any Scratch argument to an RGB color array to be used for the renderer.
     * @param {*} value Value to convert to RGB color array.
     * @return {Array.<number>} [r,g,b], values between 0-255.
     */
    function toRgbColorList(value: unknown): [number, number, number];

    /**
     * Cast any Scratch argument to an RGB color object to be used for the renderer.
     * @param {*} value Value to convert to RGB color object.
     * @return {Color.RGBOject} [r,g,b,a], values between 0-255.
     */
    function toRgbColorObject(value: unknown): Color.RGBObject;

    /**
     * Determine if a Scratch argument is a white space string (or null / empty).
     * @param {*} value value to check.
     * @return {boolean} True if the argument is all white spaces or null / empty.
     */
    function isWhiteSpace(value: unknown): boolean;

    /**
     * Determine if a Scratch argument number represents a round integer.
     * @param {*} value Value to check.
     * @return {boolean} True if number looks like an integer.
     */
    function isInt(value: unknown): boolean;

    /**
     * Returned if the index was invalid in any way.
     */
    const LIST_INVALID = 'INVALID';
    /**
     * Returned if the block is referring to all of the items in the list.
     */
    const LIST_ALL = 'ALL';

    /**
     * Compute a 1-based index into a list, based on a Scratch argument.
     * Two special cases may be returned:
     * LIST_ALL: if the block is referring to all of the items in the list.
     * LIST_INVALID: if the index was invalid in any way.
     * @param {*} index Scratch arg, including 1-based numbers or special cases.
     * @param {number} length Length of the list.
     * @param {false} acceptAll Whether it should accept "all" or not.
     * @return {(number|string)} 1-based index for list, LIST_ALL, or LIST_INVALID.
     */
    function toListIndex(
      index: unknown,
      length: number,
      acceptAll: false,
    ): number | 'INVALID';

    /**
     * Compute a 1-based index into a list, based on a Scratch argument.
     * Two special cases may be returned:
     * LIST_ALL: if the block is referring to all of the items in the list.
     * LIST_INVALID: if the index was invalid in any way.
     * @param {*} index Scratch arg, including 1-based numbers or special cases.
     * @param {number} length Length of the list.
     * @param {true} acceptAll Whether it should accept "all" or not.
     * @return {(number|string)} 1-based index for list, LIST_ALL, or LIST_INVALID.
     */
    function toListIndex(
      index: unknown,
      length: number,
      acceptAll: true,
    ): number | 'INVALID' | 'ALL';

    /**
     * Compute a 1-based index into a list, based on a Scratch argument.
     * Two special cases may be returned:
     * LIST_ALL: if the block is referring to all of the items in the list.
     * LIST_INVALID: if the index was invalid in any way.
     * @param {*} index Scratch arg, including 1-based numbers or special cases.
     * @param {number} length Length of the list.
     * @param {boolean} acceptAll Whether it should accept "all" or not.
     * @return {(number|string)} 1-based index for list, LIST_ALL, or LIST_INVALID.
     */
    function toListIndex(
      index: unknown,
      length: number,
      acceptAll: boolean,
    ): number | 'INVALID' | 'ALL';
  }

  /**
   * Methods for cloning JavaScript objects.
   */
  namespace Clone {
    /**
     * Deep-clone a "simple" object: one which can be fully expressed with JSON.
     * Non-JSON values, such as functions, will be stripped from the clone.
     * @param {object} original - the object to be cloned.
     * @returns {object} a deep clone of the original object.
     */
    function simple<T extends object>(original: T): T;
  }

  type TranslatableString =
    | string
    | {
        id?: string;
        default: string;
        description?: string;
      };

  function translate(
    string: TranslatableString,
    variables?: Record<string, string>,
  ): string;

  namespace translate {
    function setup(translations: Record<string, Record<string, string>>): void;
    /** Current language. May change while the project runs. Possible values: "en", "es", "it", etc. */
    let language: string;
  }

  /**
   * Only available when run in a scratch-gui environment (website, desktop app).
   * In other environments (packager), will be undefined.
   */
  namespace gui {
    /**
     * Lazily get the internal ScratchBlocks object when it becomes available. It may never be
     * available if, for example, the user never enters the editor.
     *
     * ScratchBlocks becoming available does not necessarily mean the user is in the editor due
     * to getBlocklyEagerly() also existing.
     */
    function getBlockly(): Promise<ScratchBlocks.RealBlockly>;

    /**
     * Get the internal ScratchBlocks object as soon as possible. This lets you access it even
     * if the user never enters the editor.
     *
     * This method is VERY SLOW and will cause A LOT OF CPU AND NETWORK ACTIVITY because it
     * downloads and evaluates all of scratch-blocks, a multi-megabyte JavaScript bundle.
     */
    function getBlocklyEagerly(): Promise<ScratchBlocks.RealBlockly>;
  }

  /**
   * Types of block notch/nub shapes
   */
  namespace NotchShape {
    /**
     * Notch shape: switchCase (switch-case).
     */
    const SWITCH: 'switchCase';

    /**
     * Notch shape: hexagonal (booleans/predicates).
     */
    const HEXAGON: 'hexagon';

    /**
     * Notch shape: rounded (numbers/strings).
     */
    const ROUND: 'round';

    /**
     * Notch shape: squared (arrays/array buffers/uint arrays).
     */
    const SQUARE: 'square';

    /**
     * pm: Notch shape: leaf-ed (vectors).
     */
    const LEAF: 'leaf';

    /**
     * pm: Notch shape: plus (objects/classes or class instances).
     */
    const PLUS: 'plus';

    /**
     * pm: Notch shape: octagonal (Scratch targets).
     */
    const OCTAGONAL: 'octagonal';

    /**
     * pm: Notch shape: bumped (BigInt).
     */
    const BUMPED: 'bumped';

    /**
     * pm: Notch shape: indented (Symbols).
     */
    const INDENTED: 'indented';

    /**
     * pm: Notch shape: scrapped (Maps).
     */
    const SCRAPPED: 'scrapped';

    /**
     * pm: Notch shape: arrow (Sets).
     */
    const ARROW: 'arrow';

    /**
     * pm: Notch shape: ticket (Dates).
     */
    const TICKET: 'ticket';

    /**
     * Doesn't really coresspond to any data type
     */
    const JIGSAW: 'jigsaw';

    /**
     * Doesn't really coresspond to any data type
     */
    const INVERTED: 'inverted';

    /**
     * Doesn't really coresspond to any data type
     */
    const PINCER: 'pincer';
  }

  /**
   * Types of block shapes
   */
  namespace BlockShape {
    /**
     * Output shape: hexagonal (booleans/predicates).
     */
    const HEXAGONAL: 1;

    /**
     * Output shape: rounded (numbers/strings).
     */
    const ROUND: 2;

    /**
     * Output shape: squared (arrays/array buffers/uint arrays).
     */
    const SQUARE: 3;

    /**
     * pm: Output shape: leaf-ed (vectors).
     */
    const LEAF: 4;

    /**
     * pm: Output shape: plus (objects/classes or class instances).
     */
    const PLUS: 5;

    /**
     * pm: Output shape: octagonal (Scratch targets).
     */
    const OCTAGONAL: 6;

    /**
     * pm: Output shape: bumped (BigInt).
     */
    const BUMPED: 7;

    /**
     * pm: Output shape: indented (Symbols).
     */
    const INDENTED: 8;

    /**
     * pm: Output shape: scrapped (Maps).
     */
    const SCRAPPED: 9;

    /**
     * pm: Output shape: arrow (Sets).
     */
    const ARROW: 10;

    /**
     * pm: Output shape: ticket (Dates).
     */
    const TICKET: 11;
  }

  /**
   * Types of argument alignments
   */
  namespace ArgumentAlignment {
    /**
     * Default alignment
     */
    const DEFAULT: null;

    /**
     * Left alignment (usually default)
     */
    const LEFT: 'LEFT';

    /**
     * Center alignment (used by the variable getter blocks)
     */
    const CENTER: 'CENTRE';

    /**
     * Right alignment (used by loop indicators)
     */
    const RIGHT: 'RIGHT';
  }

  /**
   * Block argument types
   */
  namespace ArgumentType {
    /**
     * Numeric value with angle picker
     */
    const ANGLE: 'angle';

    /**
     * Boolean value with hexagonal placeholder
     * Note that the 'B' in the BOOLEAN enums are capitalized in Scratch. It is not a typo in this file.
     */
    const BOOLEAN: 'Boolean';

    /**
     * Numeric value with color picker
     */
    const COLOR: 'color';

    /**
     * Numeric value with text field
     */
    const NUMBER: 'number';

    /**
     * String value with text field
     */
    const STRING: 'string';

    /**
     * String value with matrix field
     */
    const MATRIX: 'matrix';

    /**
     * MIDI note number with note picker (piano) field
     */
    const NOTE: 'note';

    /**
     * Inline image on block (as part of the label)
     */
    const IMAGE: 'image';

    /**
     * pm: creates an input with n x,y inputs
     */
    const POLYGON: 'polygon';

    /**
     * pm: creates an user-defined DOM input
     */
    const CUSTOM: 'custom';

    /**
     * Costume menu (taken from tw)
     */
    const COSTUME: 'costume';

    /**
     * Sound menu (taken from tw)
     */
    const SOUND: 'sound';

    /**
     * pm: Variable menu
     * @deprecated Not functioning as intended
     * @todo Fix args returning variable value instead of object
     */
    const VARIABLE: 'variable';

    /**
     * pm: List menu
     * @deprecated Not functioning as intended
     * @todo Fix menu resetting on update & args returning "[object Object]" instead of object
     */
    const LIST: 'list';

    /**
     * pm: Broadcast menu
     * @deprecated Not functioning as intended
     * @todo Fix menu resetting on update
     */
    const BROADCAST: 'broadcast';

    /**
     * pm: Vertical seperator
     */
    const SEPERATOR: 'seperator';
  }

  /**
   * Types of block
   */
  namespace BlockType {
    /**
     * Boolean reporter with hexagonal shape
     */
    const BOOLEAN: 'Boolean';

    /**
     * A button (not an actual block) for some special action, like making a variable
     */
    const BUTTON: 'button';

    /**
     * A text label (not an actual block) for adding comments or labling blocks
     */
    const LABEL: 'label';

    /**
     * Command block
     */
    const COMMAND: 'command';

    /**
     * Specialized command block which may or may not run a child branch
     * The thread continues with the next block whether or not a child branch ran.
     */
    const CONDITIONAL: 'conditional';

    /**
     * Specialized hat block with no implementation function
     * This stack only runs if the corresponding event is emitted by other code.
     */
    const EVENT: 'event';

    /**
     * Hat block which conditionally starts a block stack
     */
    const HAT: 'hat';

    /**
     * Specialized command block which may or may not run a child branch
     * If a child branch runs, the thread evaluates the loop block again.
     */
    const LOOP: 'loop';

    /**
     * General reporter with numeric or string value
     */
    const REPORTER: 'reporter';

    /**
     * Arbitrary scratch-blocks XML.
     */
    const XML: 'xml';
  }

  /**
   * Default types of Target supported by the VM
   */
  namespace TargetType {
    /**
     * Rendered target which can move, change costumes, etc.
     */
    const SPRITE: 'sprite';

    /**
     * Rendered target which cannot move but can change backdrops
     */
    const STAGE: 'stage';
  }

  interface AbstractArgument<T extends string> {
    type: T;
  }
  interface ShapedArgument {
    /**
     * This changes the shape of an argument to another block shape.
     * You can use this to make it clearer what your block takes in.
     *
     * Set this to a string for custom block shapes.
     * @link https://docs.penguinmod.com/development/extensions/api/blocks/custom-block-shape/
     */
    shape?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | string;
    /**
     * If you added `forceOutputType` to the output blocks, you also need to specify the check property.
     *
     * This ensures that only block with the same shape can be inputted.
     */
    check?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | string;
  }
  interface CustomArgument extends AbstractArgument<'custom'> {
    id: string;
    defaultValue?: any;
  }
  interface SeparatorArgument extends AbstractArgument<'seperator'> {}
  interface SoundArgument extends ShapedArgument, AbstractArgument<'sound'> {}
  interface CostumeArgument
    extends ShapedArgument, AbstractArgument<'costume'> {}
  interface AngleArgument extends ShapedArgument, AbstractArgument<'angle'> {
    /**
     * Defaults to 0.
     */
    defaultValue?: string | number;

    /**
     * If this input should be automaticaly casted to the inputs type.
     */
    exemptFromNormalization?: boolean;
  }
  interface BooleanArgument
    extends ShapedArgument, AbstractArgument<'Boolean'> {
    /**
     * If this input should be automaticaly casted to the inputs type.
     */
    exemptFromNormalization?: boolean;
  }
  interface ColorArgument extends ShapedArgument, AbstractArgument<'color'> {
    /**
     * Should be a hex color code. No alpha channel supported. Defaults to random color.
     */
    defaultValue?: string | number;

    /**
     * If this input should be automaticaly casted to the inputs type.
     */
    exemptFromNormalization?: boolean;
  }
  interface NumberArgument extends ShapedArgument, AbstractArgument<'number'> {
    /**
     * Defaults to 0.
     */
    defaultValue?: string | number;

    /**
     * The key name of the menu that should take place of this argument.
     */
    menu?: string;

    /**
     * If this input should be automaticaly casted to the inputs type.
     */
    exemptFromNormalization?: boolean;
  }
  interface StringArgument extends ShapedArgument, AbstractArgument<'string'> {
    /**
     * Defaults to empty string.
     */
    defaultValue?: string | number;

    /**
     * The key name of the menu that should take place of this argument.
     */
    menu?: string;

    /**
     * If this input should be automaticaly casted to the inputs type.
     */
    exemptFromNormalization?: boolean;
  }
  interface MatrixArgument extends ShapedArgument, AbstractArgument<'matrix'> {
    /**
     * Should be a 25 character long string of 1s and 0s.
     * Numbers are technically accepted, but be aware that due to floating point precision, some detail may be lost.
     * Technically optional, but behaves strangely with no default value.
     */
    defaultValue?: string | number;

    /**
     * If this input should be automaticaly casted to the inputs type.
     */
    exemptFromNormalization?: boolean;

    /**
     * Determines the width of the matrix.
     *
     * Defaults to 5.
     */
    matrixWidth?: number;

    /**
     * Determines the height of the matrix.
     *
     * Defaults to 5.
     */
    matrixHeight?: number;
  }
  interface NoteArgument extends ShapedArgument, AbstractArgument<'note'> {
    /**
     * Defaults to 0 ("C (0)")
     */
    defaultValue?: string | number;

    /**
     * If this input should be automaticaly casted to the inputs type.
     */
    exemptFromNormalization?: boolean;
  }
  interface ImageArgument extends AbstractArgument<'image'> {
    /**
     * The image to display.
     */
    dataURI: string;

    /**
     * The width of the image.
     */
    width?: string;

    /**
     * The height of the image.
     */
    height?: string;

    /**
     * Defaults to false.
     */
    flipRTL?: boolean;
  }
  interface PolygonArgument
    extends ShapedArgument, AbstractArgument<'polygon'> {
    /**
     * The number of nodes the polygon argument should have.
     */
    nodes?: number;

    /**
     * Defaults to 30.
     */
    defaultSize?: number;
  }

  /**
   * Represents an argument for a block.
   */
  type Argument =
    | CustomArgument
    | SeparatorArgument
    | CostumeArgument
    | SoundArgument
    | AngleArgument
    | BooleanArgument
    | ColorArgument
    | NumberArgument
    | StringArgument
    | MatrixArgument
    | NoteArgument
    | ImageArgument
    | PolygonArgument;

  /**
   * An interface that represents a branch.
   */
  interface Branch {
    /**
     * This allows you to change the shape of the notches of the branch to whatever you wish.
     * It can be used for clarifying custom types and systems!
     *
     * Some pre-made notches can be found in `Scratch.NotchShape`.
     * @link https://docs.penguinmod.com/development/extensions/api/blocks/custom-notch-shape/
     */
    accepts?: string;
  }

  /**
   * An interface used to define block switches,
   * that are used by the `Block switching` addon.
   */
  interface BlockSwitch {
    /**
     * The opcode to switch to.
     */
    opcode: string;

    /**
     * Tells the block switch addon that it shouldn't be switched.
     * Defaults to false.
     */
    isNoop?: boolean;

    /**
     * An object that tells the block switch addon which arguments map onto others.
     */
    remapArguments?: Record<string, string>;

    /**
     * Tells the addon which menu values should be used instead of the current ones.
     */
    remapMenus?: Record<string, Record<string, string>>;

    /**
     * Overwrites the text used by the addon. Overpowers `switchText`.
     */
    overwriteText?: string;

    /**
     * Define a seperate default value.
     */
    createArguments?: Record<string, string>;
  }

  /**
   * Rendered as text in the toolbox.
   */
  interface LabelBlock extends AbstractBlock {
    blockType: 'label';
  }

  /**
   * Arbitrary scratch-blocks XML.
   */
  interface XMLBlock extends AbstractBlock {
    blockType: 'xml';

    /**
     * Arbitrary scratch-blocks XML that defines this block.
     */
    xml: string;
  }

  interface AbstractBlock {
    /**
     * The text to display on this block.
     * Use an array for blocks with multiple branches.
     */
    text: string | string[];
    filter?: Array<'target' | 'sprite'>;
  }

  /**
   * An interface representing any executable block.
   */
  interface ExecutableBlock extends AbstractBlock {
    /**
     * Defines the unique id of this block.
     */
    opcode: string;

    /**
     * The name of the function to call for this block.
     * If left undefined, the opcode will be used instead.
     */
    func?: string;

    /**
     * A record containing the block's arguments.
     *
     * To use these arguments you simply put into the strings of the text value `[argName]`
     * where `argName` is the name of the argument in this list.
     */
    arguments?: Record<string, Argument>;

    /**
     * If true, the block will not appear in the toolbox.
     *
     * Use this for deprecated blocks that should not be used,
     * but still exist for compatibility reasons.
     */
    hideFromPalette?: boolean;

    /**
     * This changes the shape of an output block to another block shape.
     * You can use this to make it clearer what your block returns.
     *
     * Set this to a string for custom block shapes.
     * @link https://docs.penguinmod.com/development/extensions/api/blocks/custom-block-shape/
     */
    blockShape?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | string;

    /**
     * An override for the extensions `blockIconURI` property.
     */
    blockIconURI?: string;

    /**
     * An override for extensions `color1` property.
     *
     * The main (fill) color.
     * Should be a hex color code.
     */
    color1?: string;

    /**
     * An override for extensions `color2` property.
     *
     * The secondary and "shadow" color for rounded menus.
     * Should be a hex color code.
     */
    color2?: string;

    /**
     * An override for extensions `color3` property.
     *
     * The outline color. (also used for empty inputs)
     * Should be a hex color code.
     */
    color3?: string;

    /**
     * The color of the block text.
     * Should be a hex color code.
     */
    blockText?: string;

    /**
     * An array that defines block switches used by the `Block switching` addon.
     */
    switches?: Array<string | BlockSwitch>;

    /**
     * Overwrite text used by the `Block switching` addon.
     */
    switchText?: string;
  }

  interface BooleanBlock extends ExecutableBlock {
    blockType: 'Boolean';

    /**
     * If you only want this block to fit into other block's arguments using the same shape, then you need to add the `forceOutputType` parameter.
     *
     * Set this to a string for custom block shapes.
     *
     * @example
     *  {
     *    opcode: 'triangleCutShape',
     *    text: 'triangle cut',
     *    blockType: Scratch.BlockType.REPORTER,
     *    blockShape: "myReallyCoolExtension-triangleCut",
     *    forceOutputType: "myReallyCoolExtension-triangleCut",
     *  },
     * @link https://docs.penguinmod.com/development/extensions/api/blocks/custom-block-shape/#forceoutputtype-optional
     */
    forceOutputType?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | string;

    /**
     * Whether or not there should be a monitor checkbox for this block in the toolbox,
     * only set to true on reporter and boolean type blocks if the reporter has no arguments.
     */
    checkboxInFlyout?: boolean;

    /**
     * Antonym of `checkboxInFlyout`.
     *
     * Defaults to false.
     */
    disableMonitor?: boolean;

    /**
     * Defines the label that should be used by the block monitor.
     */
    label?: string;

    /**
     * Defines the function, under the extension class, that should be run to get the label for the block monitor.
     *
     * This function is passed an object of menu values; any variables are instead passed as their name.
     */
    labelFn?: string;
  }

  interface ButtonBlock extends AbstractBlock {
    blockType: 'button';

    /**
     * The name of the function to call when this button is pressed.
     */
    func: 'MAKE_A_LIST' | 'MAKE_A_PROCEDURE' | 'MAKE_A_VARIABLE' | string;
  }

  interface CommandBlock extends ExecutableBlock {
    blockType: 'command';

    /**
     * This allows you to change the shape of the notches in command/c-blocks to whatever you wish.
     * It can be used for clarifying custom types and systems!
     *
     * Some pre-made notches can be found in `Scratch.NotchShape`.
     * @link https://docs.penguinmod.com/development/extensions/api/blocks/custom-notch-shape/
     */
    notchAccepts?: string;

    /**
     * Determines if blocks can be placed after this one.
     *
     * Defaults to false.
     */
    isTerminal?: boolean;
  }

  interface ConditionalBlock extends ExecutableBlock {
    blockType: 'conditional';

    /**
     * This allows you to change the shape of the notches in command/c-blocks to whatever you wish.
     * It can be used for clarifying custom types and systems!
     *
     * Some pre-made notches can be found in `Scratch.NotchShape`.
     * @link https://docs.penguinmod.com/development/extensions/api/blocks/custom-notch-shape/
     */
    notchAccepts?: string;

    /**
     * Determines if blocks can be placed after this one.
     *
     * Defaults to false.
     */
    isTerminal?: boolean;

    /**
     * This changes the alignment of different things inside the block.
     *
     * There are a few things to note:
     * - Each argument is an index into the array (so adding `hello [ABC] [DEF]` will make `ABC` be the second item in the array, `DEF` be the third)
     * - Text counts as an argument (so in the above example, `hello` is the first item in the array)
     * - Branches count as arguments (its easier to see the item index for branches by looking at the block on the workspace)
     * @link https://docs.penguinmod.com/development/extensions/api/blocks/alignments/
     */
    alignments?: Array<null | 'LEFT' | 'CENTRE' | 'RIGHT'>;

    /**
     * The amount of branches this block should have.
     *
     * Defaults to 1.
     */
    branchCount?: number;

    /**
     * An array of objects (which most of the time will just be empty) that states how many branches should be on this block.
     *
     * Fallbacks to using `branchCount`.
     */
    branches?: Array<Branch>;

    /**
     * The indicator that should be appended to the end of the last leg in this block,
     * if this property is in the object but is set to null-like then the icon `./static/blocks-media/repeat.svg` is used instead.
     */
    branchIndicator?: string | null;

    /**
     * Synonym of `branchIndicator`.
     */
    branchIconURI?: string | null;
  }

  interface EventBlock extends ExecutableBlock {
    blockType: 'event';

    /**
     * This must be explicitly set to false, otherwise the block will not work.
     * Event blocks cannot be edge activated. Use hat instead.
     */
    isEdgeActivated: false;

    /**
     * Defaults to false.
     */
    shouldRestartExistingThreads?: boolean;
  }

  interface HatBlock extends ExecutableBlock {
    blockType: 'hat';

    /**
     * Defines if this block, when triggered by function evalutation,
     * should continue to trigger for every instance the output is true or
     * only trigger on instances where the output has changed to be true.
     *
     * Defaults to true.
     */
    isEdgeActivated?: boolean;

    /**
     * Defaults to false.
     */
    shouldRestartExistingThreads?: boolean;
  }

  interface ReporterBlock extends ExecutableBlock {
    blockType: 'reporter';

    /**
     * If you only want this block to fit into other block's arguments using the same shape, then you need to add the `forceOutputType` parameter.
     *
     * Set this to a string for custom block shapes.
     *
     * @example
     *  {
     *    opcode: 'triangleCutShape',
     *    text: 'triangle cut',
     *    blockType: Scratch.BlockType.REPORTER,
     *    blockShape: "myReallyCoolExtension-triangleCut",
     *    forceOutputType: "myReallyCoolExtension-triangleCut",
     *  },
     * @link https://docs.penguinmod.com/development/extensions/api/blocks/custom-block-shape/#forceoutputtype-optional
     */
    forceOutputType?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | string;

    /**
     * Whether or not there should be a monitor checkbox for this block in the toolbox,
     * only set to true on reporter and boolean type blocks if the reporter has no arguments.
     */
    checkboxInFlyout?: boolean;

    /**
     * Antonym of `checkboxInFlyout`.
     *
     * Defaults to false.
     */
    disableMonitor?: boolean;

    /**
     * Defines the label that should be used by the block monitor.
     */
    label?: string;

    /**
     * Defines the function, under the extension class, that should be run to get the label for the block monitor.
     *
     * This function is passed an object of menu values; any variables are instead passed as their name.
     */
    labelFn?: string;

    /**
     * If this block can be put into any input regardless of type.
     */
    allowDropAnywhere?: boolean;
  }

  interface LoopBlock extends ExecutableBlock {
    blockType: 'loop';

    /**
     * This allows you to change the shape of the notches in command/c-blocks to whatever you wish.
     * It can be used for clarifying custom types and systems!
     *
     * Some pre-made notches can be found in `Scratch.NotchShape`.
     * @link https://docs.penguinmod.com/development/extensions/api/blocks/custom-notch-shape/
     */
    notchAccepts?: string;

    /**
     * Determines if blocks can be placed after this one.
     *
     * Defaults to false.
     */
    isTerminal?: boolean;

    /**
     * This changes the alignment of different things inside the block.
     *
     * There are a few things to note:
     * - Each argument is an index into the array (so adding `hello [ABC] [DEF]` will make `ABC` be the second item in the array, `DEF` be the third)
     * - Text counts as an argument (so in the above example, `hello` is the first item in the array)
     * - Branches count as arguments (its easier to see the item index for branches by looking at the block on the workspace)
     * @link https://docs.penguinmod.com/development/extensions/api/blocks/alignments/
     */
    alignments?: Array<null | 'LEFT' | 'CENTRE' | 'RIGHT'>;

    /**
     * The amount of branches this block should have.
     *
     * Defaults to 1.
     */
    branchCount?: number;

    /**
     * An array of objects (which most of the time will just be empty) that states how many branches should be on this block.
     *
     * Fallbacks to using `branchCount`.
     */
    branches?: Array<Branch>;

    /**
     * The indicator that should be appended to the end of the last leg in this block,
     * if this property is in the object but is set to null-like then the icon `./static/blocks-media/repeat.svg` is used instead.
     */
    branchIndicator?: string | null;

    /**
     * Synonym of `branchIndicator`.
     */
    branchIconURI?: string | null;
  }

  /**
   * Represents a block available in the toolbox.
   */
  type Block =
    | LabelBlock
    | XMLBlock
    | BooleanBlock
    | ButtonBlock
    | CommandBlock
    | ConditionalBlock
    | EventBlock
    | HatBlock
    | ReporterBlock
    | LoopBlock;

  /**
   * Used to separate blocks in the toolbox.
   */
  type Separator = '---';

  /**
   * An interface that represents a menu.
   */
  interface Menu {
    /**
     * Determines if reporters can be put into this menu.
     *
     * False makes this a square menu.
     */
    acceptReporters?: boolean;

    /**
     * A list of static items in the menu, or the name of the dynamic menu function.
     */
    items:
      | Array<
          | string
          | {
              text: string;
              value: string;
            }
        >
      | string;
  }

  /**
   * An interface that represents a custom field type to be used with `Scratch.ArgumentType.CUSTOM`.
   */
  interface CustomFieldType {
    /**
     * the output type of this fields `allowReporters` mode as supported by the blockly block json format
     */
    output?: string | Array<string>;

    /**
     * The block shape of this fields `allowReporters` mode.
     *
     * Set this to a string for custom block shapes.
     * @link https://docs.penguinmod.com/development/extensions/api/blocks/custom-block-shape/
     */
    outputShape: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | string;

    /**
     * The field (as an extension of the Blockly.Field class) to be registered to blockly.
     *
     * Registration needs to be carried out manually.
     * @link https://docs.penguinmod.com/development/extensions/api/categories/field-types/
     */
    implementation: any;
  }

  /**
   * An object used to describe an extension.
   */
  type Info = {
    /**
     * A unique extension ID.
     */
    id: string;

    /**
     * The name of the extension.
     * Defaults to the extension ID if not specified.
     */
    name?: string;

    /**
     * The main (fill) color.
     * Should be a hex color code.
     */
    color1?: string;

    /**
     * The secondary and "shadow" color for rounded menus.
     * Should be a hex color code.
     */
    color2?: string;

    /**
     * The outline color. (also used for empty inputs)
     * Should be a hex color code.
     */
    color3?: string;

    /**
     * The text color used by executable blocks.
     * Should be a hex color code.
     */
    blockText?: string;

    /**
     * If a status button should be shown on this category,
     * used by extensions that connect to something external like the ev3 brick
     */
    showStatusButton?: boolean;

    /**
     * The extension icon; displayed in the toolbar.
     * Should be a data URI
     */
    menuIconURI?: string;

    /**
     * The block icon; displayed on all blocks before the text.
     * Should be a data URI
     */
    blockIconURI?: string;

    /**
     * If this category should update more regularly due too a seperate set of events,
     * also states if the orderBlocks function should be carried over
     */
    isDynamic?: boolean;

    /**
     * A function for handling how the contents of this category should be placed or when they should exist.
     *
     * @param blocks the unordered array of blocks.
     * @returns the ordered array of blocks.
     */
    orderBlocks?: (blocks: Array<String>) => Array<String>;

    /**
     * This is usually not included in most extensions, but you can link to another web page that explains your extension.
     * This will add a button to the top of the extension's category that links to the page.
     */
    docsURI?: string;

    /**
     * A list of block provided by the extension.
     */
    blocks?: (Block | Separator)[];

    /**
     * A list of menus that can be used as arguments in blocks.
     */
    menus?: Record<string, Menu | string[]>;
  };

  /**
   * An interface representing an extension.
   */
  interface Extension {
    getInfo(): Info;
  }

  /**
   * Contains a method for registering an extension,
   * and properties describing the current environment
   */
  namespace extensions {
    /**
     * Register a new extension.
     *
     * @param extensionObject the extension object
     */
    function register(extensionObject: Extension): void;

    /**
     * True if the extension is running unsandboxed, otherwise undefined.
     */
    const unsandboxed: undefined | boolean;

    /**
     * True if the extension is running in PenguinMod, otherwise undefined.
     */
    const isPenguinMod: undefined | boolean;
  }

  namespace external {
    /**
     * Import an ES module, like import().
     * May be inlined at build-time.
     * @param url Must be absolute and constant.
     */
    function importModule<T = unknown>(url: string): Promise<T>;
    /**
     * Returns the contents of a resource, like fetch(). Response headers may be missing.
     * May be inlined at build-time.
     * @param url Must be absolute and constant.
     */
    function fetch(url: string): Promise<Response>;
    /**
     * Returns the contents of a resource as a data: URL.
     * May be inlined at build-time.
     * @param url Must be absolute and constant.
     */
    function dataURL(url: string): Promise<string>;
    /**
     * Returns the contents of a resource as a Blob.
     * May be inlined at build-time.
     * @param url Must be absolute and constant.
     */
    function blob(url: string): Promise<Blob>;
    /**
     * Fetch a script and then evaluate it in an IIFE, returning an expression of your choice.
     * May be inlined at build-time.
     * @param url Must be absolute and constant.
     * @param returnExpression JS expression to return, usually a variable name but could be an object instead. Must be constant.
     */
    function evalAndReturn<T = unknown>(
      url: string,
      returnExpression: string,
    ): Promise<T> | T;
  }
}
